baseURL = "https://dignacouso.me/"
languageCode = "ca"
defaultContentLanguage = "ca"
title = "Digna Couso"
theme = "hyde"
[languages]
  [languages.ca]
    languageName = "Català"
    description = "Professora agregada, Universitat Autònoma de Barcelona."
    weight = 1
  [languages.en]
    languageName = "English"
    description = "Reader at the Universitat Autònoma de Barcelona."
    weight = 2
  [languages.es]
    languageName = "Español"
    description = "Profesora agregada, Universitat Autònoma de Barcelona."
    weight = 3
[params]
  twitter = "DignaCouso"
