baseURL = "https://dignacouso.me/"
languageCode = "ca"
defaultContentLanguage = "ca"
title = "Digna Couso"
theme = "hyde"
[params]
  description = "Professora agregada, Universitat Autònoma de Barcelona."
  twitter = "DignaCouso"
