baseURL: 'https://dignacouso.me/'
languageCode: ca
defaultContentLanguage: ca
title: Digna Couso
theme: hyde
languages:
  ca:
    contentDir: "content/ca/"
    languageName: Català
    weight: 1
    params:
      description: 'Professora agregada, Universitat Autònoma de Barcelona.'
  en:
    contentDir: "content/en/"
    languageName: English
    weight: 2
    params:
      description: Reader at the Universitat Autònoma de Barcelona.
  es:
    contentDir: "content/es/"
    languageName: Español
    weight: 3
    params:
      description: 'Profesora agregada, Universitat Autònoma de Barcelona.'
params:
  twitter: DignaCouso
