locale: 'ca'
backend:
  name: github
  repo: DignaCouso/dignacouso-www
media_folder: static/images
public_folder: /images
collections:
  - name: 'catalan'
    label: 'Català'
    folder: 'content/ca/'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
